Update cfupdater-dualstack

diff --git a/src/cfupdater-dualstack b/src/cfupdater-dualstack
--- a/src/cfupdater-dualstack
+++ b/src/cfupdater-dualstack
@@ -12,7 +12,7 @@ ip4=$(curl -s https://ipv4.icanhazip.com/)
 ip6=$(curl -s https://ipv6.icanhazip.com/)
 
 # SCRIPT START
-echo "[Cloudflare DDNS] Check Initiated"
+echo "[Cloudflare DDNS] $record_name, Check Initiated"
 
 # Seek for the record
 record4=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?name=$record_name&type=A" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json")
@@ -23,7 +23,7 @@ count4=$(echo "$record4" | grep -Po '(?<="count": )[0-9]*' | head -1)
 count6=$(echo "$record6" | grep -Po '(?<="count": )[0-9]*' | head -1)
 
 if [[ $count4 == 0 || $count6 == 0 ]]; then
-  >&2 echo -e "[Cloudflare DDNS] Dual stack records do not exist, perhaps create them first?"
+  >&2 echo -e "[Cloudflare DDNS] $record_name, Dual stack records do not exist, perhaps create them first?"
   exit 1
 fi
 
@@ -34,7 +34,7 @@ old_ip6=$(echo "$record6" | grep -Po '(?<="content": ")[^"]*' | head -1)
 # Compare either one is the same
 # NOTE: The script will update even one IP remains the same.
 if [[ $ip4 == $old_ip4 && $ip6 == $old_ip6 ]]; then
-  echo "[Cloudflare DDNS] IPs have not changed."
+  echo "[Cloudflare DDNS] $record_name, IPs have not changed."
   exit 0
 fi
 
@@ -51,8 +51,8 @@ success4=$(echo "$update4" | grep -Po '(?<="success": )[^,]*' | head -1)
 success6=$(echo "$update6" | grep -Po '(?<="success": )[^,]*' | head -1)
 
 if [[ $success4 == "true" && $success6 == "true" ]]; then
-  echo "[Cloudflare DDNS] IPv4 address '$ip4' and IPv6 address '$ip6' has been synced to Cloudflare."
+  echo "[Cloudflare DDNS] $record_name, IPv4 address '$ip4' and IPv6 address '$ip6' has been synced to Cloudflare."
 else
-  >&2 echo -e "[Cloudflare DDNS] Update failed. DUMPING RESULTS:\n$update4\n$update6"
+  >&2 echo -e "[Cloudflare DDNS] $record_name, Update failed. DUMPING RESULTS:\n$update4\n$update6"
   exit 1
 fi
